#ifndef _GAME_STAGE_H_
#define _GAME_STAGE_H_

enum class GameStage {
  CITY_ENTRANCE,
  DARK_FOREST,
  FORGOTTEN_ROAD,
  GOLDEN_TEMPLE,
  GREEN_FOREST,
  HAUNTED_MARKETPLACE,
  INFERNO,
  MAGIC_FOREST
};

#endif//_GAME_STAGE_H_
