#ifndef _GAME_STAGE_H_
#define _GAME_STAGE_H_

enum class GameStage {
  GREEN_FOREST,
  DARK_FOREST,
  MAGIC_FOREST,
  CITY_ENTRANCE,
  FORGOTTEN_ROAD,
  HAUNTED_MARKETPLACE,
  GOLDEN_TEMPLE,
  INFERNO
};

#endif//_GAME_STAGE_H_
