#ifndef _RESOURCE_NAME_H_
#define _RESOURCE_NAME_H_

enum class ResourceName
{
  RIGHTEOUS_FONT,
  GREAT_VIBES_FONT,
  PLAYER_TEXTURE,
  COIN_TEXTURE_1,
  COIN_TEXTURE_2,
  COIN_TEXTURE_3,
  COIN_TEXTURE_4,
  COIN_TEXTURE_5,
  PIERCED_SKULL_TEXTURE,
};

#endif //_RESOURCE_NAME_H_
