#ifndef _STAGE_NAME_H_
#define _STAGE_NAME_H_

enum class StageName {
  GREEN_FOREST,
  DARK_FOREST,
  MAGIC_FOREST,
  CITY_ENTRANCE,
  FORGOTTEN_ROAD,
  HAUNTED_MARKETPLACE,
  GOLDEN_TEMPLE,
  INFERNO
};

#endif//_STAGE_NAME_H_
